--
-- PostgreSQL database dump
--

\restrict a0KLnqmQfpFoKqpBVtmldKYHktL1yeqnXPUE81bBHXniw9fNsEacVPDuOZyafnP

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Mecanica_cliente; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Mecanica_cliente" (
    id bigint NOT NULL,
    rut character varying(12) NOT NULL,
    nombres character varying(50) NOT NULL,
    apellidos character varying(50) NOT NULL,
    telefono character varying(15) NOT NULL,
    email character varying(254) NOT NULL
);


--
-- Name: Mecanica_cliente_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Mecanica_cliente" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Mecanica_cliente_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Mecanica_marca; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Mecanica_marca" (
    id bigint NOT NULL,
    nombre character varying(50) NOT NULL
);


--
-- Name: Mecanica_marca_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Mecanica_marca" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Mecanica_marca_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Mecanica_ordentrabajo; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Mecanica_ordentrabajo" (
    id bigint NOT NULL,
    fecha_ingreso date NOT NULL,
    fecha_entrega_estimada date,
    estado character varying(15) NOT NULL,
    kilometraje_ingreso integer NOT NULL,
    observaciones text NOT NULL,
    vehiculo_id character varying(8) NOT NULL,
    CONSTRAINT "Mecanica_ordentrabajo_kilometraje_ingreso_check" CHECK ((kilometraje_ingreso >= 0))
);


--
-- Name: Mecanica_ordentrabajo_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Mecanica_ordentrabajo" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Mecanica_ordentrabajo_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Mecanica_ordentrabajo_servicios; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Mecanica_ordentrabajo_servicios" (
    id bigint NOT NULL,
    ordentrabajo_id bigint NOT NULL,
    servicio_id bigint NOT NULL
);


--
-- Name: Mecanica_ordentrabajo_servicios_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Mecanica_ordentrabajo_servicios" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Mecanica_ordentrabajo_servicios_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Mecanica_servicio; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Mecanica_servicio" (
    id bigint NOT NULL,
    nombre character varying(80) NOT NULL,
    descripcion text NOT NULL,
    precio numeric(8,0) NOT NULL
);


--
-- Name: Mecanica_servicio_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Mecanica_servicio" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Mecanica_servicio_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Mecanica_vehiculo; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Mecanica_vehiculo" (
    patente character varying(8) NOT NULL,
    modelo character varying(50) NOT NULL,
    anio integer NOT NULL,
    kilometraje integer NOT NULL,
    cliente_id bigint NOT NULL,
    marca_id bigint NOT NULL,
    CONSTRAINT "Mecanica_vehiculo_anio_check" CHECK ((anio >= 0)),
    CONSTRAINT "Mecanica_vehiculo_kilometraje_check" CHECK ((kilometraje >= 0))
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Data for Name: Mecanica_cliente; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Mecanica_cliente" (id, rut, nombres, apellidos, telefono, email) FROM stdin;
24	12.345.678-9	Carla	Muñoz	+56912345678	carla.munoz@gmail.com
25	9.876.543-2	Pedro	Salinas	+56987654321	pedro.salinas@gmail.com
26	15.234.567-0	Fernanda	Contrera	+56911223344	fer.contreras@gmail.com
27	8.111.222-3	Rodrigo	Espinoza	+56955667788	rodrigo.espinoza@gmail.com
28	17.888.999-1	Valentina	Reyes	+56933445566	valen.reyes@gmail.com
\.


--
-- Data for Name: Mecanica_marca; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Mecanica_marca" (id, nombre) FROM stdin;
23	Toyota
24	Chevrolet
25	Nissan
26	Hyundai
27	Suzuki
\.


--
-- Data for Name: Mecanica_ordentrabajo; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Mecanica_ordentrabajo" (id, fecha_ingreso, fecha_entrega_estimada, estado, kilometraje_ingreso, observaciones, vehiculo_id) FROM stdin;
9	2026-09-22	2026-09-09	entregado	45200		GKJR56
10	2026-09-22	2026-09-23	en_proceso	78100		AB1234
11	2026-09-22	\N	pendiente	15050		HTBP21
12	2026-09-22	2026-09-22	listo	32000		CD5678
13	2026-09-22	\N	pendiente	60300		JKLM90
\.


--
-- Data for Name: Mecanica_ordentrabajo_servicios; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Mecanica_ordentrabajo_servicios" (id, ordentrabajo_id, servicio_id) FROM stdin;
7	9	8
8	10	10
9	11	11
10	12	8
11	13	8
12	13	10
\.


--
-- Data for Name: Mecanica_servicio; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Mecanica_servicio" (id, nombre, descripcion, precio) FROM stdin;
9	Alineación y balanceo	Alineación de dirección y balanceo de neumáticos	35000
10	Revisión de frenos	Inspección y ajuste del sistema de frenos	19998
11	Diagnóstico computarizado	Escaneo electrónico de fallas del motor	14999
8	Cambio de aceite	Cambio de aceite y filtro	25000
\.


--
-- Data for Name: Mecanica_vehiculo; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Mecanica_vehiculo" (patente, modelo, anio, kilometraje, cliente_id, marca_id) FROM stdin;
GKJR56	Yaris	2019	45000	24	23
AB1234	Sail	2017	78000	25	24
HTBP21	Versa	2021	15000	26	25
CD5678	Accent	2020	32000	27	26
JKLM90	Swift	2018	60000	28	27
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add cliente	7	add_cliente
26	Can change cliente	7	change_cliente
27	Can delete cliente	7	delete_cliente
28	Can view cliente	7	view_cliente
29	Can add marca	8	add_marca
30	Can change marca	8	change_marca
31	Can delete marca	8	delete_marca
32	Can view marca	8	view_marca
33	Can add servicio	9	add_servicio
34	Can change servicio	9	change_servicio
35	Can delete servicio	9	delete_servicio
36	Can view servicio	9	view_servicio
37	Can add vehiculo	10	add_vehiculo
38	Can change vehiculo	10	change_vehiculo
39	Can delete vehiculo	10	delete_vehiculo
40	Can view vehiculo	10	view_vehiculo
41	Can add orden trabajo	11	add_ordentrabajo
42	Can change orden trabajo	11	change_ordentrabajo
43	Can delete orden trabajo	11	delete_ordentrabajo
44	Can view orden trabajo	11	view_ordentrabajo
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
2	pbkdf2_sha256$1000000$UfZ2UVWREmlmJZ2XAWf8BO$QtwKvgR3vfDtHglX5QBx3CIq7YQQppNJaTXss5o/iGQ=	2026-09-22 13:42:22.223231-03	f	mecanico1				f	t	2026-09-20 13:59:50.536973-03
1	pbkdf2_sha256$1000000$B52ccjYZJBVBNb7IGBkgi4$nkDUOiGrdfqQqehfTxRjYJtRYln+n7kIpMj/cY/4GEw=	2026-09-22 13:43:18.140174-03	t	administrador			administrador@gmail.com	t	t	2026-09-20 12:21:32.726381-03
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-09-22 13:43:31.672898-03	23	Toyota	1	[{"added": {}}]	8	1
2	2026-09-22 13:43:48.476449-03	24	Chevrolet	1	[{"added": {}}]	8	1
3	2026-09-22 13:43:53.913283-03	25	Nissan	1	[{"added": {}}]	8	1
4	2026-09-22 13:43:59.995926-03	26	Hyundai	1	[{"added": {}}]	8	1
5	2026-09-22 13:44:11.467216-03	27	Suzuki	1	[{"added": {}}]	8	1
6	2026-09-22 13:45:10.514023-03	24	Carla Muñoz	1	[{"added": {}}]	7	1
7	2026-09-22 13:45:37.01475-03	25	Pedro Salinas	1	[{"added": {}}]	7	1
8	2026-09-22 13:46:05.931813-03	26	Fernanda Contrera	1	[{"added": {}}]	7	1
9	2026-09-22 13:46:37.074428-03	27	Rodrigo Espinoza	1	[{"added": {}}]	7	1
10	2026-09-22 13:46:57.874091-03	28	Valentina Reyes	1	[{"added": {}}]	7	1
11	2026-09-22 13:47:21.496159-03	8	Cambio de aceite	1	[{"added": {}}]	9	1
12	2026-09-22 13:47:42.357194-03	9	Alineación y balanceo	1	[{"added": {}}]	9	1
13	2026-09-22 13:47:55.946417-03	10	Revisión de frenos	1	[{"added": {}}]	9	1
14	2026-09-22 13:48:11.758926-03	11	Diagnóstico computarizado	1	[{"added": {}}]	9	1
15	2026-09-22 13:48:25.52994-03	8	Cambio de aceite	2	[{"changed": {"fields": ["Precio"]}}]	9	1
16	2026-09-22 13:49:04.662224-03	GKJR56	GKJR56 Yaris	1	[{"added": {}}]	10	1
17	2026-09-22 14:46:07.651627-03	AB1234	AB1234 Sail	1	[{"added": {}}]	10	1
18	2026-09-22 14:46:37.301822-03	HTBP21	HTBP21 Versa	1	[{"added": {}}]	10	1
19	2026-09-22 14:47:05.654409-03	CD5678	CD5678 Accent	1	[{"added": {}}]	10	1
20	2026-09-22 14:47:27.657534-03	JKLM90	JKLM90 Swift	1	[{"added": {}}]	10	1
21	2026-09-22 14:48:25.712102-03	9	Orden #9 - GKJR56 Yaris	1	[{"added": {}}]	11	1
22	2026-09-22 14:49:04.539474-03	10	Orden #10 - AB1234 Sail	1	[{"added": {}}]	11	1
23	2026-09-22 14:49:29.738104-03	11	Orden #11 - HTBP21 Versa	1	[{"added": {}}]	11	1
24	2026-09-22 14:50:00.878627-03	12	Orden #12 - CD5678 Accent	1	[{"added": {}}]	11	1
25	2026-09-22 14:50:56.478242-03	13	Orden #13 - JKLM90 Swift	1	[{"added": {}}]	11	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	Mecanica	cliente
8	Mecanica	marca
9	Mecanica	servicio
10	Mecanica	vehiculo
11	Mecanica	ordentrabajo
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-09-17 15:16:43.525004-03
2	auth	0001_initial	2026-09-17 15:16:43.588899-03
3	admin	0001_initial	2026-09-17 15:16:43.61789-03
4	admin	0002_logentry_remove_auto_add	2026-09-17 15:16:43.621673-03
5	admin	0003_logentry_add_action_flag_choices	2026-09-17 15:16:43.62793-03
6	contenttypes	0002_remove_content_type_name	2026-09-17 15:16:43.634401-03
7	auth	0002_alter_permission_name_max_length	2026-09-17 15:16:43.645312-03
8	auth	0003_alter_user_email_max_length	2026-09-17 15:16:43.648179-03
9	auth	0004_alter_user_username_opts	2026-09-17 15:16:43.648179-03
10	auth	0005_alter_user_last_login_null	2026-09-17 15:16:43.672189-03
11	auth	0006_require_contenttypes_0002	2026-09-17 15:16:43.672189-03
12	auth	0007_alter_validators_add_error_messages	2026-09-17 15:16:43.68125-03
13	auth	0008_alter_user_username_max_length	2026-09-17 15:16:43.696041-03
14	auth	0009_alter_user_last_name_max_length	2026-09-17 15:16:43.69737-03
15	auth	0010_alter_group_name_max_length	2026-09-17 15:16:43.727514-03
16	auth	0011_update_proxy_permissions	2026-09-17 15:16:43.740608-03
17	auth	0012_alter_user_first_name_max_length	2026-09-17 15:16:43.743518-03
18	sessions	0001_initial	2026-09-17 15:16:43.775065-03
19	Mecanica	0001_initial	2026-09-17 17:55:37.279524-03
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
7t6p23goj0jyat94emq9wychtjouxbfs	.eJxVjEEOwiAQRe_C2pBCGYou3XsGMjMMUjU0Ke3KeHfbpAvd_vfef6uI61Li2mSOY1IX1avT70bIT6k7SA-s90nzVJd5JL0r-qBN36Ykr-vh_h0UbGWr2YO1IIZy5o48M58ZPQTJEmBg5xKYIUjHIhTcZuZgAyQUJmugd-rzBQ2vOM0:1x8zvv:zAHRMa5c4LE3pPVw5vaX5zx5N9T5sKGDk67DDMlwN4Y	2026-10-06 09:49:15.544727-03
tek2awzihnhk9y39ewr6rwmqs5pelysj	.eJxVjEEOwiAQRe_C2hCGIgWX7nsGwjCDVA0kpV0Z765NutDtf-_9lwhxW0vYOi9hJnERRpx-N4zpwXUHdI_11mRqdV1mlLsiD9rl1Iif18P9Oyixl28NihEBMGHKVltgN4IiMjobjWcavQNEp5XBwXpn3MDZZ-1BeZ2BGMT7A-hjN50:1x8zw6:80Pj1RmcB1sbzo7FkDHGMMhSFewDO_455NsV-U8Wtoc	2026-10-06 09:49:26.209422-03
aumq5t72n1i8ke3szmk6ll07iavvq19f	.eJxVjDsOwjAQBe_iGlnxL2tR0nMGa-PdxQHkSHFSIe4OllJA-2bmvVTCfStpb7ymmdRZBXX63SbMD64d0B3rbdF5qds6T7or-qBNXxfi5-Vw_w4KttJrT2SYOcog1okYBgKXYSAQL459RAwOPAYwXzfCmBHRMou1PLqs3h8Z9jkr:1x90Fd:fvLOkHD1t5Ek6HOBo4tReAy1IBKzQxUqSOoL4GQRzac	2026-10-06 10:09:37.967194-03
esisf5ub94s1e44oq5vcx5mkqtkjs94b	.eJxVjLsOAiEQAP-F2hAuB8tiae83EHaXk1MDyT0q478ryRXazkzmpWLatxL3NS9xFnVWoE6_jBI_cu1C7qnemuZWt2Um3RN92FVfm-Tn5Wj_BiWtpW9JRhIcwfKITB7FOJhCgMFw8M6iZ4cgA08GPAYwJojNaC17oi9S7w_THzcQ:1x90Fn:O9khnUS6l3PXEKv9BvRK_pw9Z7AGYiUVzaDcU16okJg	2026-10-06 10:09:47.634772-03
xtk8hzwm0kccxwkxqf42qq2s9sjkyhhu	.eJxVjEsOwjAMBe-SNYrcOq0Tluw5Q-XGNimgVupnhbg7VOoCtm9m3st1vK2l2xadu0Hc2ZE7_W4954eOO5A7j7fJ52lc56H3u-IPuvjrJPq8HO7fQeGlfOtMyYxZpIGMsalqSoTIiDUYB1OqTCCGFjilFjQmpBZ6UNMgRgnd-wPoUje5:1x90G0:_tdkj8LLchCzjiL2L7YuEgLfkw5_e7dfORreqpys6fs	2026-10-06 10:10:00.487605-03
28b7qvvth2byj5ehrotu2xz9oemfaohx	.eJxVjMEOwiAQRP-FsyGAwFaP3vsNzbK7laqBpLQn47_bJj3ocea9mbcacF3ysDaZh4nVVXXq9NslpKeUHfADy71qqmWZp6R3RR-06b6yvG6H-3eQseVtjQzWCwXxwCwpgjhDXsBd5Oy6xC4aB1sKaAmiHS0gBEMuAQvZ0avPF_QQOAY:1x90Gn:10aXG6gAZN7Rkq4uEFSZ6jHIYswsNamzx3a-ktj3Aq8	2026-10-06 10:10:49.227912-03
qao3k7toe6afnj0mz9jglrmrtza079pr	.eJxVjb0OwyAQg9-FuUIQdPx07N5nQHAHJW0FUkimqO9eImVoR9uf7Z35sK3Fbz0tfiZ2ZZZdfr0Y8JXqEdAz1Efj2Oq6zJEfCD_Tzu-N0vt2sn8DJfQy2tI5MIlATdpmYeTQUSRCQpstOMwIEESW6AxFFEo7DZM1oMZFkjayzxfeRTf0:1x90XW:PLAqrB-YwGHO1UfONMMqoK2RQ8cn0oSnosd6VI90I30	2026-10-06 10:28:06.20847-03
r3o60mauog93spfkf9b1llu46k5lx5zj	.eJxVjEsOwjAMRO-SNYrqpC4NS_acobJrmxZQIvWzQtydVuoCljPvzbxdR-sydOusUzeKu7jWnX47pv6peQfyoHwvvi95mUb2u-IPOvtbEX1dD_fvYKB52NapIoSECEIGemYDbhImZcaoIFZJrBW3aBBAuQl1iAHIUhMtSGvu8wX07Dhf:1x90Xi:tdNlzdFNAbnOeG_0v1FJzab-QeKpztAGGaUpu_yC9O8	2026-10-06 10:28:18.623529-03
lvb3j5c88zq3grc1hr71fzybku0jlzon	.eJxVjDsOwjAQBe_iGlmWHWdtSnrOYO0vOIASKU4qxN0hUgpo38y8lym4rbVsTZcyijmbZE6_GyE_dNqB3HG6zZbnaV1GsrtiD9rsdRZ9Xg7376Biq996yNlHhJgHVPBEkLTj5DxLzBxd0iRM2EOXPQR1yBp6EYlEKggBzPsD_Io44A:1x90be:PE-WGtvnPGFfTywl0bKuIhRbJQ3WH-TE4kIpiJ8JeAY	2026-10-06 10:32:22.43047-03
6bjkyw31fxsfcgpi2zkun7v11sbohegv	.eJxVjDsOwjAQRO_iGln2-rempM8ZrI3XwQGUSHFSIe4OQSmgG817M0-RaFtr2lpZ0sjiLFCcfrue8r1MO-AbTddZ5nlal7GXuyIP2mQ3c3lcDvfvoFKrn7WhrDy5YMhonQckAhg8gkPNzmbQBhhJAUeyFlVE9hhUDOWbCojXG82kNvA:1x90kr:C4hqVjvRrQTZm-49aokxeYzKEIqfidUWrrw6AJNgOXs	2026-10-06 10:41:53.736696-03
qz4kl5cxgkdjz39gmf4hhkr0f68csjig	.eJxVjMsOwiAURP-FtSHyaAGX7v0Gch8gVQNJaVfGf7dNutDMbs6ZeYsI61Li2tMcJxYX4cXpt0OgZ6o74AfUe5PU6jJPKHdFHrTLW-P0uh7u30GBXrZ11l6nbFFRBnW27HgwlkMiNTChQ-uJTEAe9RYfIHttbM6cUJvRAYrPFwgDOM4:1x90o3:ok475h8jmt_74BSxMQ1unhuTEbv2Jht9LdXEJ8rTUMU	2026-10-06 10:45:11.233107-03
xrxjd0wcm3hjayfqjovmfy9m6pel4p6s	.eJxVjDsOwjAQRO_iGllaO_5R0nMGa71r4wBypDipIu5OIqWAYpp5b2YTEdelxrXnOY4srsKLy2-XkF65HYCf2B6TpKkt85jkociTdnmfOL9vp_t3ULHXfQ0OmQCsNkYjmxAGdoasdQCU2aJPxe1RuhBpwyEwoB9IGSgevMri8wXixDfo:1x913H:IG-JjMytDm6YeM6poHwdAmLi3YLjmPOKMkx-s1VSuOc	2026-10-06 11:00:55.718584-03
st4amdvxg78bghelq118pxw7bjpa5sqk	.eJxVjEEOwiAURO_C2hCgFD4u3XsGAvyPVA0kpV0Z764kXehqknlv5sV82Lfi906rX5CdGbDTbxdDelAdAO-h3hpPrW7rEvlQ-EE7vzak5-Vw_w5K6GWsXbIZjYxuVkgCJ5PAzEjWKaG1sQEMiElISzYryFqDklEmEpTNNzR7fwDegjeK:1x91XY:3zR8RuBv40yv7EcMUd_zYrXtu9xI8aumg77GBF_bRZM	2026-10-06 11:32:12.842576-03
a3wmiptahend9l9jwf67lpjc2y82ifjj	.eJxVjDsOwjAQRO_iGlnxevGHkp4zWGt7gwPIluKkQtydREoBzRTz3sxbBFqXEtbOc5iyuAgnTr9dpPTkuoP8oHpvMrW6zFOUuyIP2uWtZX5dD_fvoFAv2xocsEFGcGOO1jN5chZg9NlqrRFNQhy2TIa9V0RpUA6sPYMhUhSV-HwB06s3TQ:1x91ZE:erJKDrZc9YjgQ2H_6_4EIweLInrrkvFK95Z9ovLO6Xw	2026-10-06 11:33:56.724367-03
7562gsg9axxs3ekyjia9fze7xmsh559q	.eJxVjEEOwiAQRe_C2hAgUMCle89AZphBqgaS0q6Md9cmXej2v_f-SyTY1pq2wUuaSZxFEKffDSE_uO2A7tBuXebe1mVGuSvyoENeO_Hzcrh_BxVG_dbWKgMeC9ioMVDMcVLRFWKwuViKqHSeHARil7lEYzwQECpQQaNxXrw_AUU4wg:1x91ff:SQ7LxvTOoWAYhJscvHIRfaXDhDMltxgGdqqNuqUcetI	2026-10-06 11:40:35.217006-03
l14tp5k8fyl619pdy497jga7269tzf5l	.eJxVjDsOgzAQBe_iOrL8wWY3ZXrOgLy7diCJQMJQRbl7QKJI2pl57636tK1Dv9W89KOoqwJ1-WWU-JmnQ8gjTfdZ8zyty0j6SPRpq-5mya_b2f4dDKkO-9qRB-EGbQGIzqALxIYxCBkIPkYsZKkU43YiGNCiQLbec9MytBHU5wvWqDdm:1x91iO:wUgKeqdPNPD7-3QH1Nm4lZ_18CARLYgD0ujpixZzYjg	2026-10-06 11:43:24.696951-03
7ppd6q9exwv8kl56pfacgpqp7ej1k9mc	.eJxVjMsOwiAQRf-FtSEML8Gl-34DGWCQqoGktCvjv2uTLnR7zzn3xQJuaw3boCXMmV2YY6ffLWJ6UNtBvmO7dZ56W5c58l3hBx186pme18P9O6g46rfWHpPyWljlvBRKk6BEYEsuQGcLMZFzslgPxVsDWZIzVsqovSmAhgx7fwDRZDdf:1x91qA:KqaWKDN8aydo1tTtpA2JBYA3OI1pJExQoIZop_aY1UQ	2026-10-06 11:51:26.236792-03
3z22q9nb59wg3bdpesjqgfupvsam9pxt	.eJxVjMEOwiAQRP-FsyEsXZR69N5vaFjYlaqBpLQn47_bJj1o5jbvzbzVGNYlj2vjeZySuiqvTr8dhfjksoP0COVedaxlmSfSu6IP2vRQE79uh_t3kEPL27pD78X0gkBCiNBhOIvbAhcbyBpnACwnAWYXE4iLaEl6bwwRskvq8wXfMDgk:1x91v2:0gthr6YhJKu2gXWoB8jgpQOGSmtLOrcxJ3Cf-cfeJgI	2026-10-06 11:56:28.434413-03
8kf4hw3f3gx1sdhjl0xvb9zw0wpa9g20	.eJxVjEEOwiAQRe_C2hAYOhVcuu8ZyMCAVA0kpV0Z765NutDtf-_9l_C0rcVvPS1-ZnERVpx-t0DxkeoO-E711mRsdV3mIHdFHrTLqXF6Xg_376BQL98a1ADJcHRnGDNBILQOQoxaIyKhYmuMQTZW26w0ZGfjmDIwqTAwBhbvD9O_N8g:1x9202:KggSiEw6Q7zkxGySByU8C3UlwZccGVyOWavkwFVY8YA	2026-10-06 12:01:38.335878-03
2u0x1qwr0crjpfftk69fzmh53s03fjc0	.eJxVjEEOwiAQRe_C2hAEpK1L9z1DM8PMSNVAUtqV8e7SpAvdvvf-f6sJtjVNW-VlmkldVa9OvwwhPjnvgh6Q70XHktdlRr0n-rBVj4X4dTvav4MENbW1ByPBe-iCIIXOY0_BIFuyJoAQAFsRcK1xzlxo4DCIOzcWLYNFrz5fBmE47A:1x922Y:Pfx_VHWTiEGMpPczlxWUNR-fdu8q06ufKUFCzIO7kdY	2026-10-06 12:04:14.190905-03
igu7pz7heks86cpfbnozl5qqxwbn3oyh	.eJxVjEEOwiAQRe_C2hBsmQ516b5nIMwMSNVAUtqV8e7apAvd_vfefykftjX7rcXFz6IuyqnT70aBH7HsQO6h3KrmWtZlJr0r-qBNT1Xi83q4fwc5tPyto00A2HEfBZyMjBZwNGDSmUmMILiQBsEoiWhgFMtEAS1j39vOGlbvD_0LOKI:1x922l:52ezqepkpt_FXMWyeteQjmpqFAGqrbQbu6cNHs16Oao	2026-10-06 12:04:27.155869-03
him55dabkv4u5w7quy6detehinjr3y1k	.eJxVjDsOwjAQBe_iGllrx19Kes5geb0bHEC2lE-FuDtESgHtm5n3Eilva03bwnOaSJxFEKffDXN5cNsB3XO7dVl6W-cJ5a7Igy7y2omfl8P9O6h5qd9aYQRj0EZSGmwG5R1Zp8bIDFAsBOMCFvKKBu2GbByMyJ4dGMV6wCjeH79XNwU:1x92mD:Bzl0uQT8z70U6iQ27Q8zjfQk0F4Bldu25mRPsus4xSY	2026-10-06 12:51:25.627082-03
b43r7zbgbv3umvpmwgduiy7i4dwr7bbm	.eJxVjE0OwiAYRO_C2hAQoeDSfc9Avh-QqoGktCvj3W2TLnQ5897MW0RYlxLXnuY4sbgKL06_HQI9U90BP6Dem6RWl3lCuSvyoF2OjdPrdrh_BwV62dYmK02QlGYdtHEcrAL0ChGDxbNLyNbli4PAHgkZvAHcMhPmgXgg8fkCAR85eA:1x938V:I3ghrLXMzfHxdVST4ugr21j6UJS920DVNodDau7s4HM	2026-10-06 13:14:27.823921-03
n7jsc98wizz51u5gg7i5aea79xnfvasa	.eJxVjMsOwiAUBf-FtSFUKA-X7v0Gwn0gVQNJaVfGfzckXej2zMx5i5j2rcS98xoXEhfhxel3g4RPrgPQI9V7k9jqti4ghyIP2uWtEb-uh_t3UFIvo-Y5sOGsziqY7JMODkNCi6BnMt4pAj9plVkh6km5AGyDtQSWNGvI4vMF-BY4dg:1x93Fj:yhiE4ur7zw3dbA7uWlxXrALCfPzG_OICVzcpTgrrN1o	2026-10-06 13:21:55.759821-03
vn6dszl2b59hvgmoyh563yiaxl5jrih9	.eJxVjDkOwjAQRe_iGll4G48p6XMGa7wMCSBbylIh7g6RUkD733v_JSJt6xi3pc5xKuIiUJx-t0T5UdsOyp3arcvc2zpPSe6KPOgih17q83q4fwcjLeO3TsHaosEQYGCuuThnFWc0jBQMKQCCqguq5JndGTCD9iZ4zQZryijeH-7JN_8:1x93N3:XQlHowsLmeqFb3kMNsGWUugrNoD3idiWL1_4q7Nu6Ek	2026-10-06 13:29:29.231898-03
11qf3l4eg5dqmhiril1k41ec4354uehg	.eJxVjTEOwyAUQ-_CXCFI-AQ6ds8ZEPwPJW0FUkimqncvkTK0Hu1n-82c37fs9hZXtxC7Mskuv17w-IzlCOjhy71yrGVbl8APhJ9p43Ol-Lqd7N9A9i33NoBF8NoShjSqLgQAbcYkVUCK2gJETEKAApEkJT1OAwzUD8xkDUn2-QLc5je0:1x93aQ:Eb1y4OUXVdhncf3OR8fkEI_odb-OwGzaBHDlFlyhMmg	2026-10-06 13:43:18.142889-03
\.


--
-- Name: Mecanica_cliente_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Mecanica_cliente_id_seq"', 28, true);


--
-- Name: Mecanica_marca_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Mecanica_marca_id_seq"', 27, true);


--
-- Name: Mecanica_ordentrabajo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Mecanica_ordentrabajo_id_seq"', 13, true);


--
-- Name: Mecanica_ordentrabajo_servicios_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Mecanica_ordentrabajo_servicios_id_seq"', 12, true);


--
-- Name: Mecanica_servicio_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Mecanica_servicio_id_seq"', 11, true);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 44, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 8, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 25, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 11, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 19, true);


--
-- Name: Mecanica_cliente Mecanica_cliente_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Mecanica_cliente"
    ADD CONSTRAINT "Mecanica_cliente_pkey" PRIMARY KEY (id);


--
-- Name: Mecanica_cliente Mecanica_cliente_rut_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Mecanica_cliente"
    ADD CONSTRAINT "Mecanica_cliente_rut_key" UNIQUE (rut);


--
-- Name: Mecanica_marca Mecanica_marca_nombre_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Mecanica_marca"
    ADD CONSTRAINT "Mecanica_marca_nombre_key" UNIQUE (nombre);


--
-- Name: Mecanica_marca Mecanica_marca_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Mecanica_marca"
    ADD CONSTRAINT "Mecanica_marca_pkey" PRIMARY KEY (id);


--
-- Name: Mecanica_ordentrabajo Mecanica_ordentrabajo_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Mecanica_ordentrabajo"
    ADD CONSTRAINT "Mecanica_ordentrabajo_pkey" PRIMARY KEY (id);


--
-- Name: Mecanica_ordentrabajo_servicios Mecanica_ordentrabajo_se_ordentrabajo_id_servicio_0ee538f6_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Mecanica_ordentrabajo_servicios"
    ADD CONSTRAINT "Mecanica_ordentrabajo_se_ordentrabajo_id_servicio_0ee538f6_uniq" UNIQUE (ordentrabajo_id, servicio_id);


--
-- Name: Mecanica_ordentrabajo_servicios Mecanica_ordentrabajo_servicios_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Mecanica_ordentrabajo_servicios"
    ADD CONSTRAINT "Mecanica_ordentrabajo_servicios_pkey" PRIMARY KEY (id);


--
-- Name: Mecanica_servicio Mecanica_servicio_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Mecanica_servicio"
    ADD CONSTRAINT "Mecanica_servicio_pkey" PRIMARY KEY (id);


--
-- Name: Mecanica_vehiculo Mecanica_vehiculo_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Mecanica_vehiculo"
    ADD CONSTRAINT "Mecanica_vehiculo_pkey" PRIMARY KEY (patente);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: Mecanica_cliente_rut_8684306b_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "Mecanica_cliente_rut_8684306b_like" ON public."Mecanica_cliente" USING btree (rut varchar_pattern_ops);


--
-- Name: Mecanica_marca_nombre_3a5850a0_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "Mecanica_marca_nombre_3a5850a0_like" ON public."Mecanica_marca" USING btree (nombre varchar_pattern_ops);


--
-- Name: Mecanica_ordentrabajo_servicios_ordentrabajo_id_97ff51b4; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "Mecanica_ordentrabajo_servicios_ordentrabajo_id_97ff51b4" ON public."Mecanica_ordentrabajo_servicios" USING btree (ordentrabajo_id);


--
-- Name: Mecanica_ordentrabajo_servicios_servicio_id_a3c4e041; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "Mecanica_ordentrabajo_servicios_servicio_id_a3c4e041" ON public."Mecanica_ordentrabajo_servicios" USING btree (servicio_id);


--
-- Name: Mecanica_ordentrabajo_vehiculo_id_a3e2a4fa; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "Mecanica_ordentrabajo_vehiculo_id_a3e2a4fa" ON public."Mecanica_ordentrabajo" USING btree (vehiculo_id);


--
-- Name: Mecanica_ordentrabajo_vehiculo_id_a3e2a4fa_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "Mecanica_ordentrabajo_vehiculo_id_a3e2a4fa_like" ON public."Mecanica_ordentrabajo" USING btree (vehiculo_id varchar_pattern_ops);


--
-- Name: Mecanica_vehiculo_cliente_id_23ba26d1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "Mecanica_vehiculo_cliente_id_23ba26d1" ON public."Mecanica_vehiculo" USING btree (cliente_id);


--
-- Name: Mecanica_vehiculo_marca_id_4475e981; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "Mecanica_vehiculo_marca_id_4475e981" ON public."Mecanica_vehiculo" USING btree (marca_id);


--
-- Name: Mecanica_vehiculo_patente_497ed8c4_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "Mecanica_vehiculo_patente_497ed8c4_like" ON public."Mecanica_vehiculo" USING btree (patente varchar_pattern_ops);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: Mecanica_ordentrabajo_servicios Mecanica_ordentrabaj_ordentrabajo_id_97ff51b4_fk_Mecanica_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Mecanica_ordentrabajo_servicios"
    ADD CONSTRAINT "Mecanica_ordentrabaj_ordentrabajo_id_97ff51b4_fk_Mecanica_" FOREIGN KEY (ordentrabajo_id) REFERENCES public."Mecanica_ordentrabajo"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: Mecanica_ordentrabajo_servicios Mecanica_ordentrabaj_servicio_id_a3c4e041_fk_Mecanica_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Mecanica_ordentrabajo_servicios"
    ADD CONSTRAINT "Mecanica_ordentrabaj_servicio_id_a3c4e041_fk_Mecanica_" FOREIGN KEY (servicio_id) REFERENCES public."Mecanica_servicio"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: Mecanica_ordentrabajo Mecanica_ordentrabaj_vehiculo_id_a3e2a4fa_fk_Mecanica_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Mecanica_ordentrabajo"
    ADD CONSTRAINT "Mecanica_ordentrabaj_vehiculo_id_a3e2a4fa_fk_Mecanica_" FOREIGN KEY (vehiculo_id) REFERENCES public."Mecanica_vehiculo"(patente) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: Mecanica_vehiculo Mecanica_vehiculo_cliente_id_23ba26d1_fk_Mecanica_cliente_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Mecanica_vehiculo"
    ADD CONSTRAINT "Mecanica_vehiculo_cliente_id_23ba26d1_fk_Mecanica_cliente_id" FOREIGN KEY (cliente_id) REFERENCES public."Mecanica_cliente"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: Mecanica_vehiculo Mecanica_vehiculo_marca_id_4475e981_fk_Mecanica_marca_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Mecanica_vehiculo"
    ADD CONSTRAINT "Mecanica_vehiculo_marca_id_4475e981_fk_Mecanica_marca_id" FOREIGN KEY (marca_id) REFERENCES public."Mecanica_marca"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict a0KLnqmQfpFoKqpBVtmldKYHktL1yeqnXPUE81bBHXniw9fNsEacVPDuOZyafnP

